sudo: required

services:
 - docker

before_install:
 - mkdir -p output
 - docker pull asciidoctor/docker-asciidoctor

script:
  - ls -l $TRAVIS_BUILD_DIR 
  - docker run -it -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor asciidoc-to-html doc/*.adoc

after_error: 
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_success:      
  - cd output ; mv README.html index.html;

