sudo: required

services:
 - docker

before_install:
 - mkdir -p output
 - docker pull asciidoctor/docker-asciidoctor

script:
  - ls -l $TRAVIS_BUILD_DIR 
  - docker run -it -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor  asciidoctor doc/*.adoc

after_error: 
  - docker logs asciidoctor

after_failure:
  - docker logs asciidoctor

after_success:      
  - cd output ;  ls -l ;mv README.html index.html;

